spring:
  application:
    name: backend

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

entities:
  user:
    modifier: 10
    stIdx: 0
