server:
  port: ${PORT:8090}

spring:
  rabbitmq:
    listener:
      simple:
        concurrency: 2
        max-concurrency: 4

broker:
  queue: code-processor
  exchange: rabbit_mq_exchange
  key: rabbit_mq_r_key
  login:
    username: guest
    password: guest
    address: ${BROKER_ADDRESS:localhost}
    port: 5672

app:
  docker:
    compiler:
      timeout-in-seconds: 30
      path: ${APP_DOCKERFILE_PATH:./code-compiler-consumer/dockerCompiler}
    docker-host: ${APP_DOCKER_HOST:tcp://localhost:2375}

logging:
  level:
    http.server.queue: trace